sudo: required
dist: trusty
language: node_js
# Keep empty to use version from .nvmrc
node_js:

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable


matrix:
  fast_finish: true

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - npm run ci:travis
  - npm run build:prod

after_success:
  - npx semantic-release
