language: node_js
# Keep empty to use version from .nvmrc
node_js: null

cache:
  directories:
    - node_modules

install:
  - npm ci

script:
  - npm run lint
  - npm rum test
  - npm run build

after_success:
  - npx semantic-release
