sudo: false
language: node_js

# Keep empty to use value from .nvmrc
node_js:

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run build

after_success:
  - npm run semantic-release
