sudo: false
dist: trusty
language: node_js

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

node_js:
  - "7"

matrix:
  fast_finish: true

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - npm run ci:travis

after_success:
  - npm run semantic-release
